WIP: Add potal UI helm chart
virtualresearchenvironment/helm-charts pull request #2
Opened 2021-11-24 20:35 UTC by mnaghavi

2021-11-25 14:03 UTC, andricDu requested changes

2021-11-25 14:03 UTC, andricDu commented on portal/values.yaml
> +  port: 80
this value does not appear to be used in your deployment.

2021-11-25 14:03 UTC, andricDu commented on portal/values.yaml
> +  repository: nginx
even though we are currently using the private registry, we can just use the name of the image we create for now. I'm assuming it's something like `portal`.

2021-11-25 14:05 UTC, andricDu commented on portal/values.yaml
> +  port: 80
Looks like this is not even configurable for our portal image if you inspect the docker file.

2021-11-25 14:52 UTC, mnaghavi commented on portal/values.yaml
> +  port: 80
Yes, you're right. removed

2021-11-25 14:59 UTC, mnaghavi commented on portal/values.yaml
> +  repository: nginx
That makes sence. changed.

2021-11-26 14:04 UTC, andricDu approved these changes

2021-11-26 14:06 UTC, merged